// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReadingList.Persistence;

#nullable disable

namespace ReadingList.Persistence.Migrations
{
    [DbContext(typeof(ReadingListDbContext))]
    [Migration("20221207073523_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReadingList.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Finished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrioNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Finished = false,
                            Name = "First",
                            PrioNumber = 4
                        },
                        new
                        {
                            Id = 2,
                            Finished = false,
                            Name = "Second",
                            PrioNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            Finished = false,
                            Name = "Third",
                            PrioNumber = 1
                        },
                        new
                        {
                            Id = 4,
                            Finished = false,
                            Name = "Fourth",
                            PrioNumber = 3
                        },
                        new
                        {
                            Id = 5,
                            Finished = false,
                            Name = "Fifth",
                            PrioNumber = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
